services:
  postgres_workspace:
    restart: always
    container_name: postgres_workspace
    image: postgres:15
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -V" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: -p ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  migrations:
    build:
      context: .
      dockerfile: Dockerfile_migrations
    env_file:
      - .env
    depends_on:
      - postgres_workspace

  app:
    restart: always
    container_name: app
    build: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres_workspace

volumes:
  postgres_volume:
